network:
  - {u: 0, v: 1, bandwidth: 124}
  - {u: 0, v: 2, bandwidth: 124}
  - {u: 1, v: 6, bandwidth: 124}
  - {u: 2, v: 6, bandwidth: 124}
  - {u: 1, v: 8, bandwidth: 124}
  - {u: 8, v: 9, bandwidth: 124}
  - {u: 6, v: 7, bandwidth: 124}
  - {u: 3, v: 4, bandwidth: 124}
  - {u: 4, v: 5, bandwidth: 124}
  - {u: 3, v: 7, bandwidth: 124}
  - {u: 5, v: 7, bandwidth: 124}
  - {u: 5, v: 9, bandwidth: 124}

settings:
  pkg_distr:
    sequence:
      - {pkg_number: 100, delta: 10}
      - {pkg_number: 500, delta: 10, sources: [0, 1, 2, 6], dests: [3, 4, 5, 7]}
      - {action: 'break_link', pause: 20, u: 6, v: 7}
      - {pkg_number: 500, delta: 10, sources: [0, 1, 2, 6], dests: [3, 4, 5, 7]}
      - {action: 'break_link', pause: 20, u: 0, v: 1}
      - {pkg_number: 500, delta: 10, sources: [0, 1, 2, 6], dests: [3, 4, 5, 7]}
      - {action: 'break_link', pause: 20, u: 4, v: 5}
      - {pkg_number: 500, delta: 10, sources: [0, 1, 2, 6], dests: [3, 4, 5, 7]}
      - {action: 'restore_link', pause: 20, u: 6, v: 7}
      - {pkg_number: 500, delta: 10, sources: [0, 1, 2, 6], dests: [3, 4, 5, 7]}
      - {action: 'restore_link', pause: 20, u: 0, v: 1}
      - {pkg_number: 500, delta: 10, sources: [0, 1, 2, 6], dests: [3, 4, 5, 7]}
      - {action: 'restore_link', pause: 20, u: 4, v: 5}
      - {pkg_number: 500, delta: 10, sources: [0, 1, 2, 6], dests: [3, 4, 5, 7]}
  logging:
    delta: 500
  router_env:    
    pkg_process_delay: 5
  router:
    simple_q:
      learning_rate: 0.5
